### ISSUE TITLE
Ignored a pile of tests to get Selenium 3.0 out

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/htmlunit-driver#26]
See the changes in: https://github.com/SeleniumHQ/selenium/commit/bf47492f6596872f214ded935802ce47c802dcde

**Comment by asashour** [comment]
Thanks Simon for pointing to that commit.

I am closing the issue, since all tests now either pass in `master`, `2.25` branch, or are outside the scope of HtmlUnit (element location).

Also, please note whenever HtmlUnit fails, it is preferred to mark it as `@NotYetImplemented` instead of `@Ignore`.
