### ISSUE TITLE
Synchronize version of httpmime and htmlunit dependencies between htmlunit-driver and over Selenium artifacts 

### ISSUE THREAD

**Issue by skabashnyuk** [SeleniumHQ/htmlunit-driver#42]
I was trying to use 
org.seleniumhq.selenium:htmlunit-driver:2.25
org.seleniumhq.selenium:selenium-remote-driver:3.1.0
with Dependency convergence enabled in maven but I couldn't.

WARNING]
Dependency convergence error for org.apache.httpcomponents:httpmime:4.5.3 paths to dependency are:
+-com.codenvy.qa:qa-core:1.0-SNAPSHOT
  +-org.seleniumhq.selenium:htmlunit-driver:2.25
    +-net.sourceforge.htmlunit:htmlunit:2.25
      +-org.apache.httpcomponents:httpmime:4.5.3
and
+-com.codenvy.qa:qa-core:1.0-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-remote-driver:3.1.0
    +-org.apache.httpcomponents:httpmime:4.5.2

[WARNING]
Dependency convergence error for net.sourceforge.htmlunit:htmlunit:2.25 paths to dependency are:
+-com.codenvy.qa:qa-core:1.0-SNAPSHOT
  +-org.seleniumhq.selenium:htmlunit-driver:2.25
    +-net.sourceforge.htmlunit:htmlunit:2.25
and
+-com.codenvy.qa:qa-core:1.0-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-java:3.1.0
    +-net.sourceforge.htmlunit:htmlunit:2.23

**Comment by asashour** [comment]
Thanks for feedback, I didn't know about Dependency convergence.

Now it as been added by https://github.com/SeleniumHQ/htmlunit-driver/commit/f6bfd79619909a0a1351c8360b09c9b81cafa9e5, and will be used in HtmlUnit later.

I believe you need to exclude `net.sourceforge.htmlunit:htmlunit` from `org.seleniumhq.selenium:selenium-java`, since they have different lifecycles.

Also, you can exclude `org.seleniumhq.selenium:selenium-remote-driver` from `org.seleniumhq.selenium:selenium-remote-driver`.
